//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yoko.Templates {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Templates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Templates() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Yoko.Templates.Templates", typeof(Templates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die package ${GROUP}.${NAME};
        ///
        ///import org.bukkit.plugin.java.JavaPlugin;
        ///
        ///public class Main extends JavaPlugin {
        ///
        ///	@Override
        ///	public void onEnable() {
        ///		getLogger().info(&quot;Hello World!&quot;);
        ///	}
        ///	
        ///} ähnelt.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die name: ${NAME}
        ///main: ${GROUP}.${NAME}.Main
        ///api-version: ${MCVERSION}
        ///version: 1.0
        ///commands: ähnelt.
        /// </summary>
        public static string plugin {
            get {
                return ResourceManager.GetString("plugin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;version&quot;: &quot;0.2.0&quot;,
        ///	&quot;configurations&quot;: [
        ///		{
        ///			&quot;type&quot;: &quot;java&quot;,
        ///			&quot;name&quot;: &quot;Attach&quot;,
        ///			&quot;request&quot;: &quot;attach&quot;,
        ///			&quot;hostName&quot;: &quot;localhost&quot;,
        ///			&quot;port&quot;: &quot;5005&quot;,
        ///			&quot;preLaunchTask&quot;: &quot;build and run&quot;
        ///		}
        ///	]
        ///} ähnelt.
        /// </summary>
        public static string vscode_launch {
            get {
                return ResourceManager.GetString("vscode.launch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///    &quot;java.project.sourcePaths&quot;: [&quot;src/main/java&quot;],
        ///    &quot;java.project.referencedLibraries&quot;: {
        ///        &quot;include&quot;:[],
        ///        &quot;sources&quot;: {}
        ///    },
        ///    &quot;java.configuration.runtimes&quot;: [
        ///        {
        ///            &quot;name&quot;: &quot;JavaSE-&quot;,
        ///            &quot;default&quot;: true,
        ///            &quot;path&quot;: &quot;&quot;
        ///        }
        ///    ]
        ///}
        /// ähnelt.
        /// </summary>
        public static string vscode_settings {
            get {
                return ResourceManager.GetString("vscode.settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die {
        ///	&quot;version&quot;: &quot;2.0.0&quot;,
        ///	&quot;tasks&quot;: [
        ///		{
        ///			&quot;label&quot;: &quot;build and run&quot;,
        ///			&quot;type&quot;: &quot;shell&quot;,
        ///			&quot;command&quot;: &quot;mcplugin test&quot;,
        ///			&quot;isBackground&quot;: true,
        ///			&quot;problemMatcher&quot;: {
        ///				&quot;owner&quot;: &quot;custom&quot;,
        ///				&quot;pattern&quot;: { &quot;regexp&quot;: &quot;__________&quot; },
        ///				&quot;background&quot;: {
        ///					&quot;activeOnStart&quot;: true,
        ///					&quot;beginsPattern&quot;: &quot;^building plugin\\.\\.\\.$&quot;,
        ///					&quot;endsPattern&quot;: &quot;^Listening for transport dt_socket at address: 5005$&quot;
        ///				}
        ///			}
        ///		}
        ///	]
        ///} ähnelt.
        /// </summary>
        public static string vscode_tasks {
            get {
                return ResourceManager.GetString("vscode.tasks", resourceCulture);
            }
        }
    }
}
